# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
   - go mod download
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  binary: docker-machine-driver-equinix-metal
  ldflags:
   - -X github.com/packethost/docker-machine-driver-equinix-metal/pkg/drivers/equinix-metal/equinix-metal.version={{.Version}}
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm64
    - goos: darwin
      goarch: arm
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
# replacements:
#    darwin: Darwin
#    linux: Linux
#    windows: Windows
#    386: i386
#    amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
